<?php

namespace PI\Premium_ImmobilierBundle\Repository;

/**
 * ProcontratRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProcontratRepository extends \Doctrine\ORM\EntityRepository
{
}
