<?php

namespace PI\Premium_ImmobilierBundle\Repository;
use PI\Premium_ImmobilierBundle\Entity\Reservation;
use Doctrine\ORM\EntityRepository;
use PI\Premium_ImmobilierBundle\Entity\TypeBien;
use PI\Premium_ImmobilierBundle\Entity\Localite;
use PI\Premium_ImmobilierBundle\Entity\Bien;
use PI\Premium_ImmobilierBundle\Entity\Image;

use Doctrine\ORM\QueryBuilder;
/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{

    public function countReservation($idbien){
    $qb = $this
    ->createQueryBuilder('r')
    ->select('COUNT(r)')
    ->where('r.bien_id = :idbien')
    ->setParameter('idbien',$idbien);
    return $qb
    ->getQuery()
    ->getSingleScalarResult();
    }


     /** Touver la list des reservations */
      public function listReservation()
    {
        $dql = "SELECT r,b,i FROM PI\Premium_ImmobilierBundle\Entity\Reservation r
        left Join  r.client c  Join  r.bien b Join  b.TypeBien t Join b.Localite l  Join b.images i where r.etat='0' and b.etat='1' ";
        $query = $this->getEntityManager()->createQuery($dql);

        return $query->getResult();
    }



      public function findReservationById($id)
    {
        $dql = "SELECT r,b,i FROM PI\Premium_ImmobilierBundle\Entity\Reservation r
        left Join  r.client c  Join  r.bien b Join  b.TypeBien t Join b.Localite l  Join b.images i where r.id= :id";
        $query = $this->getEntityManager()->createQuery($dql);
        $query->setParameter('id', $id);

        return $query->getResult();
    }


    
}
