<?php

namespace PI\Premium_ImmobilierBundle\Repository;

/**
 * textContratRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class textContratRepository extends \Doctrine\ORM\EntityRepository
{
}
